# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 14:41
from __future__ import unicode_literals

from django.db import migrations
import recapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('recapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='array',
            field=recapp.models.JSONField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='array',
            field=recapp.models.JSONField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='arrayratedmoviesindxs',
            field=recapp.models.JSONField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lastrecs',
            field=recapp.models.JSONField(),
        ),
    ]
